import { Lead } from './types';

export const mockLeads: Lead[] = [
  {
    id: 'lead-1',
    name: 'Francisco Silva',
    contact_source: 'Website',
    contact_date: '2026-03-22',
    phone: '911362949',
    email: 'tatianaleit@gmail.com',
    class_type: 'GBK',
    next_contact_date: '',
    followup_note: '',
    status: 'Por contactar',
    trial_date: '',
    enrolled: false,
  },
  {
    id: 'lead-2',
    name: 'Andre Lopes',
    contact_source: 'Alunos GBCQ',
    contact_date: '2026-03-27',
    phone: '',
    email: '',
    class_type: 'GB1',
    next_contact_date: '',
    followup_note: '',
    status: 'Aula agendada',
    trial_date: '',
    enrolled: false,
  },
  {
    id: 'lead-3',
    name: 'Francisco Arriaga',
    contact_source: 'Outros',
    contact_date: '2026-03-19',
    phone: '964299620',
    email: '',
    class_type: 'GB1',
    next_contact_date: '2026-03-23',
    followup_note: '',
    status: 'Aula realizada',
    trial_date: '',
    enrolled: false,
  },
  {
    id: 'lead-4',
    name: 'Matilde Lisboa Leão',
    contact_source: 'Outros',
    contact_date: '2026-03-14',
    phone: '',
    email: '',
    class_type: 'GBK',
    next_contact_date: '',
    followup_note: '',
    status: 'Por contactar',
    trial_date: '',
    enrolled: false,
  },
  {
    id: 'lead-5',
    name: 'João Dinis Pereira Candela',
    contact_source: 'Alunos GBCQ',
    contact_date: '2026-03-14',
    phone: '917894474',
    email: 'joaodniscandelası@g',
    class_type: 'GB1',
    next_contact_date: '',
    followup_note: '',
    status: 'Aula agendada',
    trial_date: '',
    enrolled: false,
  },
  {
    id: 'lead-6',
    name: 'Rodrigo Garrido Oliveira',
    contact_source: 'Alunos GBCQ',
    contact_date: '2026-03-11',
    phone: '',
    email: '',
    class_type: 'GB1',
    next_contact_date: '',
    followup_note: '',
    status: 'Por contactar',
    trial_date: '',
    enrolled: false,
  },
  {
    id: 'lead-7',
    name: 'Vítor Dalhem Costa',
    contact_source: 'Outros',
    contact_date: '2026-03-21',
    phone: '910268262',
    email: 'dalbemcosta@gmail.c',
    class_type: 'GB1',
    next_contact_date: '2026-03-22',
    followup_note: '',
    status: 'Contactado',
    trial_date: '',
    enrolled: false,
  },
  {
    id: 'lead-8',
    name: 'Tiago Matias',
    contact_source: 'Outros',
    contact_date: '2026-03-20',
    phone: '935145573',
    email: '',
    class_type: 'GBK',
    next_contact_date: '2026-03-31',
    followup_note: '',
    status: 'Contactado',
    trial_date: '',
    enrolled: false,
  },
  {
    id: 'lead-9',
    name: 'Cassia da Silva',
    contact_source: 'Instagram',
    contact_date: '2026-03-20',
    phone: '915386550',
    email: '',
    class_type: 'GBK',
    next_contact_date: '2026-03-24',
    followup_note: 'Follow up para inscrição',
    status: 'Aula realizada',
    trial_date: '2026-03-20',
    enrolled: false,
  },
  {
    id: 'lead-10',
    name: 'João Maria Sousa Martins',
    contact_source: 'Instagram',
    contact_date: '2026-03-06',
    phone: '966940260',
    email: 'joamartins@aluno.a',
    class_type: 'GB1',
    next_contact_date: '',
    followup_note: '',
    status: 'Aula agendada',
    trial_date: '',
    enrolled: false,
  },
  {
    id: 'lead-11',
    name: 'Vasco Nunes Albano',
    contact_source: 'Alunos GBCQ',
    contact_date: '2026-03-03',
    phone: '930506485',
    email: 'vascobanos5@gmail.com',
    class_type: 'GB1',
    next_contact_date: '2026-03-03',
    followup_note: 'Estava a articular-se com o Diogo. Diz que se inscreve em Dezembro',
    status: 'Contactado',
    trial_date: '',
    enrolled: false,
  },
  {
    id: 'lead-12',
    name: 'Anne Karoline',
    contact_source: 'Outros',
    contact_date: '2026-03-19',
    phone: '925445432',
    email: '',
    class_type: 'GB1',
    next_contact_date: '2026-03-22',
    followup_note: '',
    status: 'Contactado',
    trial_date: '',
    enrolled: false,
  },
  {
    id: 'lead-13',
    name: 'Francisco Luis Gil Duarte',
    contact_source: 'Outros',
    contact_date: '2026-03-11',
    phone: '968061064',
    email: 'franciscoluisduarte@g',
    class_type: 'GBK',
    next_contact_date: '2026-03-28',
    followup_note: '',
    status: 'Contactado',
    trial_date: '',
    enrolled: false,
  },
  {
    id: 'lead-14',
    name: 'Ricardo',
    contact_source: 'Outros',
    contact_date: '2026-02-28',
    phone: '925106011',
    email: '',
    class_type: 'GB1',
    next_contact_date: '2026-03-05',
    followup_note: '',
    status: 'Nao inscrito',
    trial_date: '',
    enrolled: false,
    not_enrolled_reason: 'Sem tempo',
  },
  {
    id: 'lead-15',
    name: 'Amanda dos Santos Beavi',
    contact_source: 'Outros',
    contact_date: '2026-03-10',
    phone: '931732506',
    email: 'amandaboavida@gm',
    class_type: 'GBK',
    next_contact_date: '2026-03-10',
    followup_note: '',
    status: 'Por contactar',
    trial_date: '',
    enrolled: false,
  },
  {
    id: 'lead-16',
    name: 'Pedro e Yasmin Linhares',
    contact_source: 'Outros',
    contact_date: '2026-03-27',
    phone: '910772892',
    email: '',
    class_type: 'GBK',
    next_contact_date: '',
    followup_note: '',
    status: 'Contactado',
    trial_date: '',
    enrolled: false,
  },
  {
    id: 'lead-17',
    name: 'Mayara Guimaraes Silva',
    contact_source: 'Instagram',
    contact_date: '2026-03-20',
    phone: '932585229',
    email: 'mayara.enufar@gma',
    class_type: 'GB1',
    next_contact_date: '2026-03-31',
    followup_note: '',
    status: 'Aula realizada',
    trial_date: '2026-03-31',
    enrolled: false,
  },
  {
    id: 'lead-18',
    name: 'Matilde Cambeta',
    contact_source: 'Alunos GBCQ',
    contact_date: '2026-03-12',
    phone: '911080181',
    email: 'isabelabuquerque@g',
    class_type: 'GBK',
    next_contact_date: '',
    followup_note: '',
    status: 'Inscrito',
    trial_date: '',
    enrolled: true,
  },
  {
    id: 'lead-19',
    name: 'Vasco Pinheiro Pinto',
    contact_source: 'Outros',
    contact_date: '2026-03-16',
    phone: '965568647',
    email: 'dmi.pinto@gmail.com',
    class_type: 'GBK',
    next_contact_date: '2026-03-31',
    followup_note: '',
    status: 'Contactado',
    trial_date: '',
    enrolled: false,
  },
  {
    id: 'lead-20',
    name: 'Diogo Gomes',
    contact_source: 'Walk in',
    contact_date: '2026-03-16',
    phone: '914483624',
    email: 'dvgomes@outlook.co',
    class_type: 'GBK',
    next_contact_date: '2026-03-31',
    followup_note: '',
    status: 'Contactado',
    trial_date: '',
    enrolled: false,
  },
  {
    id: 'lead-21',
    name: 'Duarte Rodrigues',
    contact_source: 'Outros',
    contact_date: '2026-03-12',
    phone: '916882021',
    email: 'duarterodrigues91@g',
    class_type: 'GB1',
    next_contact_date: '15-12-2025',
    followup_note: '',
    status: 'Contactado',
    trial_date: '',
    enrolled: false,
  },
  {
    id: 'lead-22',
    name: 'Elisa Reis',
    contact_source: 'Instagram',
    contact_date: '2026-03-12',
    phone: '',
    email: '',
    class_type: 'GB2',
    next_contact_date: '2026-03-11',
    followup_note: '',
    status: 'Contactado',
    trial_date: '2026-03-11',
    enrolled: false,
  },
  {
    id: 'lead-23',
    name: 'Claudia Silva',
    contact_source: 'Alunos GBCQ',
    contact_date: '2026-03-12',
    phone: '918761567',
    email: '',
    class_type: 'GB1',
    next_contact_date: '',
    followup_note: '',
    status: 'Por contactar',
    trial_date: '',
    enrolled: false,
  },
  {
    id: 'lead-24',
    name: 'Marco (art of fight)',
    contact_source: 'Outros',
    contact_date: '2026-03-16',
    phone: '936631479',
    email: '',
    class_type: 'GBK',
    next_contact_date: '2026-03-17',
    followup_note: '',
    status: 'Contactado',
    trial_date: '',
    enrolled: false,
  },
];
