import { Lead, LeadRequest, LeadStats } from './types';

export const mockLeads: Lead[] = [
  {
    id: 'lead-1',
    name: 'João Silva',
    phone: '+351912345678',
    email: 'joao@example.com',
    source: 'Walk-in',
    status: 'Trial Attended',
    owner: 'Professor Ana',
    lastContact: '2026-03-15',
    nextFollowUp: '2026-03-20',
    tags: ['interested', 'adult', 'gi'],
    notes: ['Attended trial on 15th', 'Very interested in gi classes'],
    created_at: '2026-03-10',
  },
  {
    id: 'lead-2',
    name: 'Maria Costa',
    phone: '+351923456789',
    source: 'WhatsApp',
    status: 'Trial Booked',
    owner: 'Professor Carlos',
    lastContact: '2026-03-14',
    nextFollowUp: '2026-03-22',
    tags: ['nogi', 'weekend'],
    notes: ['Prefers no-gi classes', 'Weekend availability preferred'],
    created_at: '2026-03-12',
  },
  {
    id: 'lead-3',
    name: 'Pedro Oliveira',
    phone: '+351934567890',
    email: 'pedro@example.com',
    source: 'Referral',
    status: 'New',
    owner: 'Unassigned',
    tags: ['kids-program', 'family'],
    notes: ['Referred by current member João', 'Asking about kids classes'],
    created_at: '2026-03-16',
  },
  {
    id: 'lead-4',
    name: 'Sofia Martins',
    phone: '+351945678901',
    source: 'Email',
    status: 'Contacted',
    owner: 'Professor Ana',
    lastContact: '2026-03-16',
    nextFollowUp: '2026-03-18',
    tags: ['beginner', 'female'],
    notes: ['First time interested in BJJ', 'Sent welcome email'],
    created_at: '2026-03-16',
  },
  {
    id: 'lead-5',
    name: 'Bruno Santos',
    phone: '+351956789012',
    source: 'Walk-in',
    status: 'Lost',
    owner: 'Professor Carlos',
    lastContact: '2026-03-10',
    tags: ['schedule-conflict'],
    notes: ['No availability on our schedule times', 'Will try again in future'],
    created_at: '2026-02-28',
  },
];

export const mockRequests: LeadRequest[] = [
  {
    id: 'req-1',
    name: 'João Silva',
    email: 'joao@example.com',
    phone: '+351912345678',
    status: 'Trial Done',
    trialDate: '2026-03-15',
    requestedAt: '2026-03-10',
    notes: 'Ready to sign up this week',
  },
  {
    id: 'req-2',
    name: 'Ana Ferreira',
    email: 'ana@example.com',
    phone: '+351967890123',
    status: 'Accepted',
    trialDate: '2026-03-14',
    requestedAt: '2026-03-08',
    notes: 'Joined adult program, monday/wednesday',
  },
  {
    id: 'req-3',
    name: 'Tiago Gonçalves',
    phone: '+351978901234',
    status: 'Trial Pending',
    requestedAt: '2026-03-14',
    notes: 'Trial scheduled for tomorrow at 18:00',
  },
  {
    id: 'req-4',
    name: 'Mariana Rocha',
    email: 'mariana@example.com',
    phone: '+351989012345',
    status: 'No-show',
    trialDate: '2026-03-12',
    requestedAt: '2026-03-10',
    notes: 'Missed first trial, reschedule',
  },
  {
    id: 'req-5',
    name: 'Lucas Alves',
    phone: '+351990123456',
    status: 'Rejected',
    requestedAt: '2026-03-06',
    notes: 'Declined membership offer',
  },
];

export const mockLeadStats: LeadStats = {
  leadsThisWeek: 6,
  leadsThisMonth: 18,
  conversionRate: '45%',
  noShowRate: '12%',
  avgTimeToConvert: '7.2 days',
  leadsBySource: {
    'Walk-in': 8,
    'Email': 3,
    'WhatsApp': 4,
    'Referral': 2,
    'Social Media': 1,
  },
};
