import { Lead, LeadRequest, LeadStats } from './types';

export const mockLeads: Lead[] = [
  {
    id: 'lead-1',
    name: 'João Silva',
    contact_source: 'Walk-in',
    contact_date: '2026-03-10',
    phone: '+351912345678',
    email: 'joao@example.com',
    class_type: 'GB1',
    notes: 'Attended trial on 15th. Very interested in gi classes.',
    next_contact_date: '2026-03-20',
    followup_note: 'Call to confirm subscription this week.',
    status: 'trial_done',
    trial_date: '2026-03-15',
    enrolled: false,
  },
  {
    id: 'lead-2',
    name: 'Maria Costa',
    contact_source: 'Instagram',
    contact_date: '2026-03-12',
    phone: '+351923456789',
    class_type: 'GB2',
    notes: 'Prefers no-gi classes. Weekend availability preferred.',
    next_contact_date: '2026-03-22',
    followup_note: 'Check if saturday class works for her.',
    status: 'trial_booked',
    trial_date: '2026-03-21',
    enrolled: false,
  },
  {
    id: 'lead-3',
    name: 'Pedro Oliveira',
    contact_source: 'Alunos GBCQ',
    contact_date: '2026-03-16',
    phone: '+351934567890',
    email: 'pedro@example.com',
    class_type: 'GBK',
    notes: 'Referred by member João. Asking about kids classes.',
    next_contact_date: '2026-03-18',
    followup_note: 'Send kids schedule and trial info.',
    status: 'new',
    enrolled: false,
  },
  {
    id: 'lead-4',
    contact_source: 'Website',
    contact_date: '2026-03-16',
    name: 'Sofia Martins',
    class_type: 'GB1',
    notes: 'First time interested in BJJ.',
    next_contact_date: '2026-03-18',
    followup_note: 'Confirm trial booking by email.',
    status: 'contacted',
    enrolled: false,
  },
  {
    id: 'lead-5',
    contact_source: 'Outros',
    contact_date: '2026-02-28',
    name: 'Bruno Santos',
    class_type: 'GB2',
    notes: 'No availability on our schedule times.',
    next_contact_date: '2026-03-05',
    followup_note: 'Could not align timetable.',
    status: 'lost',
    enrolled: false,
    not_enrolled_reason: 'No time',
  },
];

export const mockRequests: LeadRequest[] = [
  {
    id: 'req-1',
    name: 'João Silva',
    email: 'joao@example.com',
    phone: '+351912345678',
    status: 'Trial Done',
    trialDate: '2026-03-15',
    requestedAt: '2026-03-10',
    notes: 'Ready to sign up this week',
  },
  {
    id: 'req-2',
    name: 'Ana Ferreira',
    email: 'ana@example.com',
    phone: '+351967890123',
    status: 'Accepted',
    trialDate: '2026-03-14',
    requestedAt: '2026-03-08',
    notes: 'Joined adult program, monday/wednesday',
  },
  {
    id: 'req-3',
    name: 'Tiago Gonçalves',
    phone: '+351978901234',
    status: 'Trial Pending',
    requestedAt: '2026-03-14',
    notes: 'Trial scheduled for tomorrow at 18:00',
  },
  {
    id: 'req-4',
    name: 'Mariana Rocha',
    email: 'mariana@example.com',
    phone: '+351989012345',
    status: 'No-show',
    trialDate: '2026-03-12',
    requestedAt: '2026-03-10',
    notes: 'Missed first trial, reschedule',
  },
  {
    id: 'req-5',
    name: 'Lucas Alves',
    phone: '+351990123456',
    status: 'Rejected',
    requestedAt: '2026-03-06',
    notes: 'Declined membership offer',
  },
];

export const mockLeadStats: LeadStats = {
  leadsThisWeek: 6,
  leadsThisMonth: 18,
  conversionRate: '45%',
  noShowRate: '12%',
  avgTimeToConvert: '7.2 days',
  leadsBySource: {
    'Walk-in': 8,
    'Website': 3,
    'Instagram': 4,
    'WhatsApp': 4,
    'Alunos GBCQ': 2,
    'Outros': 1,
  },
};
